// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcv_-Q9FKutr4zw_7G7leFVOJU3jIEHFs',
    appId: '1:208308398050:web:da0dfa2173c0dd301f3bbb',
    messagingSenderId: '208308398050',
    projectId: 'microstep-d03c6',
    authDomain: 'microstep-d03c6.firebaseapp.com',
    storageBucket: 'microstep-d03c6.firebasestorage.app',
    measurementId: 'G-0Q0G2CJTHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDraV0TjRHaB8T003lY6AtDpxb0HdEvwwM',
    appId: '1:208308398050:android:19773d4ffe43932d1f3bbb',
    messagingSenderId: '208308398050',
    projectId: 'microstep-d03c6',
    storageBucket: 'microstep-d03c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeNoapcystiM6ikSRBEFK3xR5gq8l8Ybw',
    appId: '1:208308398050:ios:7c9aebc116a8d6c81f3bbb',
    messagingSenderId: '208308398050',
    projectId: 'microstep-d03c6',
    storageBucket: 'microstep-d03c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationHomepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeNoapcystiM6ikSRBEFK3xR5gq8l8Ybw',
    appId: '1:208308398050:ios:7c9aebc116a8d6c81f3bbb',
    messagingSenderId: '208308398050',
    projectId: 'microstep-d03c6',
    storageBucket: 'microstep-d03c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationHomepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcv_-Q9FKutr4zw_7G7leFVOJU3jIEHFs',
    appId: '1:208308398050:web:dbb3baa57fbc6f381f3bbb',
    messagingSenderId: '208308398050',
    projectId: 'microstep-d03c6',
    authDomain: 'microstep-d03c6.firebaseapp.com',
    storageBucket: 'microstep-d03c6.firebasestorage.app',
    measurementId: 'G-B26942X254',
  );
}
